#ifndef header_h
#define header_h

String file1=
"<html>\r\n"
"<head>\r\n"
"<title>ESP8266 Line Follower Robot Monitor</title>\r\n"
"<meta charset=\"UTF-8\">\r\n"
"<script type=\"text/javascript\" src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\r\n"
"<script type=\"text/javascript\">\r\n"
"var dps = [];\r\n"
"var sensordps =[\r\n"
"  { y: 200, label: \"S0\" },\r\n"
"  { y: 200,  label: \"S1\" },\r\n"
"  { y: 200,  label: \"S2\" },\r\n"
"  { y: 200,  label: \"S3\" },\r\n"
"  { y: 200,  label: \"S4\" },\r\n"
"  { y: 200, label: \"S5\" },\r\n"
"  { y: 200,  label: \"S6\" },\r\n"
"  { y: 200,  label: \"S7\" },\r\n"
"  { y: 200,  label: \"S8\" },\r\n"
"  { y: 200,  label: \"S9\" },\r\n"
"  { y: 200,  label: \"S10\" }\r\n"
"];\r\n"
"var errdps= [\r\n"
"			{ x: 10, y:[0, -2], label: \"Error\" },\r\n"
"			{ x: 20, y:[0, 1.25], label: \"Error Proporcional\" },\r\n"
"			{ x: 30, y:[1.25, -1], label: \"Error Integral\" },\r\n"
"			{ x: 40, y:[-1, -2], label: \"Error Derivacional\" }\r\n"
"		];\r\n"
"var yVal = 0;\r\n"
"var chart;\r\n"
"var senchart;\r\n"
"var errchart;\r\n"
"var connection;\r\n"
"var ep=0.00;var ei=0.00;var ed=0.00;\r\n"
"var dataLength = 50;\r\n"
"window.onload=Pinstatus;\r\n"
"function Pinstatus(){\r\n"
"connection = new WebSocket('ws://";
String file2=":81/');\r\n"
"connection.onopen = function () {\r\n"
"  console.log('Connected');\r\n"
"};\r\n"
"connection.onerror = function (error) {\r\n"
"  console.log('WebSocket Error ', error);\r\n"
"};\r\n"
"connection.onmessage = function (e) {\r\n"
"  updateasyncstatus(e.data);\r\n"
"};\r\n"
"connection.onclose = function () {\r\n"
"  console.log('WebSocket connection closed');\r\n"
"};\r\n"
"chart = new CanvasJS.Chart(\"posContainer\", {\r\n"
"	animationEnabled:true,\r\n"
"	title :{\r\n"
"		text: \"Posicion\"\r\n"
"	},\r\n"
"	axisY: {\r\n"
"		includeZero: false\r\n"
"	},      \r\n"
"	axisX: {\r\n"
"		maximum: 12.0,\r\n"
"		minimum: 0.0,\r\n"
"stripLines: [\r\n"
"			{\r\n"
"				startValue: 5,\r\n"
"				endValue: 7,\r\n"
"				opacity: 1.0\r\n"
"			}\r\n"
"			]\r\n"
"	},      \r\n"
"	data: [{\r\n"
"		type: \"spline\",\r\n"
"		dataPoints: dps\r\n"
"	}]\r\n"
"});\r\n"
"senchart = new CanvasJS.Chart(\"sensorContainer\", {\r\n"
"animationEnabled: true,\r\n"
"theme: \"light1\",\r\n"
"title :{\r\n"
"		text: \"Sensores\"\r\n"
"	},\r\n"
"	axisY: {\r\n"
"		maximum: 255,\r\n"
"		minimum: 0\r\n"
"	},      \r\n"
"	data: [{\r\n"
"		type: \"column\",\r\n"
"		dataPoints: sensordps\r\n"
"	}]\r\n"
"});\r\n"
"errchart = new CanvasJS.Chart(\"errorContainer\", {\r\n"
"	animationEnabled: true,\r\n"
"	title: {\r\n"
"		text: \"Error\"\r\n"
"	},\r\n"
"	axisX: {\r\n"
"		title: \"Errores\"\r\n"
"	},\r\n"
"	axisY: {\r\n"
"		maximum: 6.0,\r\n"
"		minimum: -6.0,\r\n"
"		includeZero: true\r\n"
"	}, \r\n"
"	data: [{\r\n"
"		type: \"rangeBar\",\r\n"
"		dataPoints: errdps\r\n"
"	}]\r\n"
"});\r\n"
"chart.render();\r\n"
"errchart.render();\r\n"
"senchart.render();\r\n"
"}\r\n"

"function updateasyncstatus(result){\r\n"
"document.getElementById(\"description\").innerHTML = result;\r\n"
"fullset = JSON.parse(result);\r\n"
"if (typeof fullset.KP != \"undefined\")\r\n"
"{\r\n"
"    document.getElementById(\"kp\").value = fullset.KP;\r\n"
"}\r\n"
"if(typeof fullset.KI != \"undefined\")\r\n"
"{\r\n"
"    document.getElementById(\"ki\").value = fullset.KI;\r\n"
"}\r\n"
"if(typeof fullset.KD != \"undefined\")\r\n"
"{\r\n"
"    document.getElementById(\"kd\").value = fullset.KD;\r\n"
"}\r\n"
"dps.push({x: fullset.POS,y: yVal});\r\n"
"yVal++;\r\n"
"if (dps.length > dataLength) {\r\n"
"  dps.shift();\r\n"
"}\r\n"
"chart.render();\r\n"
"    ep = fullset.EP;\r\n"
"    ei = fullset.EI;\r\n"
"    ed = fullset.ED;\r\n"
" sensordps[0].y=fullset.S0;\r\n"
" sensordps[1].y=fullset.S1;\r\n"
" sensordps[2].y=fullset.S2;\r\n"
" sensordps[3].y=fullset.S3;\r\n"
" sensordps[4].y=fullset.S4;\r\n"
" sensordps[5].y=fullset.S5;\r\n"
" sensordps[6].y=fullset.S6;\r\n"
" sensordps[7].y=fullset.S7;\r\n"
" sensordps[8].y=fullset.S8;\r\n"
" sensordps[9].y=fullset.S9;\r\n"
" sensordps[10].y=fullset.S10;\r\n"
" errdps[1].y[1]=ep;\r\n"
" errdps[2].y[0]=ep;\r\n"
" errdps[2].y[1]=ep+ei;\r\n"
" errdps[3].y[0]=ep+ei;\r\n"
" errdps[3].y[1]=ep+ei+ed;\r\n"
" errdps[0].y[1]=ep+ei+ed;\r\n"
"errchart.render();\r\n"
" senchart.render();\r\n"
"}\r\n"
"function sendbutton(Pin,action){\r\n"
"document.getElementById(\"description\").innerHTML = \"Processing Button Click\";\r\n"
"val= document.getElementById(action).value;\r\n"
"if(action!=\"spd\"){\r\n"
"document.getElementById(action).value=0;\r\n"
"}\r\n"
"connection.send(Pin+val);\r\n"
"}\r\n"
"</script>\r\n"
"</head>\r\n"
"<body><font face=\"Arial\" style=\"display:flex;  flex-wrap:wrap;\">\r\n"
"<table name=\"Table\" cellpadding=\"6\" border=\"1\" style=\"width:100%;\">\r\n"
"<tbody><tr><td align=\"center\">Constante Proporcional<br>\r\n"
"<input style=\"text-align: center;\" size=\"6\" id=\"kp\" name=\"kp\" value=\"0.00\" step=\"0.01\" type=\"number\"><button onclick=\"sendbutton('P','kp');\">Enviar KP</button>\r\n"
"</td><td align=\"center\">Constante Integral<br>\r\n"
"<input style=\"text-align: center;\" size=\"6\" id=\"ki\" value=\"0.00\" name=\"kp\" step=\"0.01\" type=\"number\"><button onclick=\"sendbutton('I','ki');\">Enviar KI</button>\r\n"
"</td><td align=\"center\">Constante Derivacional<br>\r\n"
"<input style=\"text-align: center;\" size=\"6\" id=\"kd\" name=\"kd\" value=\"0.00\" step=\"0.01\" type=\"number\"><button onclick=\"sendbutton('D','kd');\">Enviar KD</button>\r\n"
"</td><td align=\"center\">Delay<br>\r\n"
"<input style=\"text-align: center;\" size=\"6\" id=\"spd\" name=\"spd\" value=\"1000\" step=\"10\" type=\"number\"><button onclick=\"sendbutton('S','spd');\">Enviar Delay</button>\r\n"
"</td></tr>\r\n"
"</tbody></table>\r\n"
"<div id=\"sensorContainer\" style=\"height: 255px; width:100%;\"></div>\r\n"
"<div id=\"posContainer\" style=\"height: 500px; width:100%;\"></div>\r\n"
"<div id=\"errorContainer\" style=\"height: 100px; width:100%;\"></div>\r\n"
"<p id=\"description\">Processing Status</p>\r\n"
"</font>\r\n"
"<span style=\"position: absolute; left: 0px; top: -20000px; padding: 0px; margin: 0px; border: medium none; white-space: pre; line-height: normal; font-family: Trebuchet MS, Helvetica, sans-serif; font-size: 13px; font-weight: normal; display: none;\">Mpgyi</span></body>\r\n"
"</html>\r\n";

#endif
